[package]
name = "vsr"
version = "0.1.0"
edition = "2024"

[dependencies]
bincode = "2.0.1"
crossbeam = "0.8.4"
polling = "3.7.4"
rand = "0.9.1"
rand_chacha = "0.9.0"
thiserror = "2.0.12"
tracing = "0.1.41"

[dev-dependencies]
lazy_static = "1.5.0"
